version: '3'

services:
  consul:
    image: consul:1.8.4
    container_name: consul_dashboard__consul
    ports:
      - 8500:8500
    command: ["consul", "agent", "-server", "-ui", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-bootstrap", "-datacenter", "docker", "-dev"]
